2.exe:	main_2.c manipula_array.s inverte_array.s
	gcc -o 2.exe main_2.c manipula_array.s inverte_array.s

debug:	main_2.c manipula_array.s inverte_array.s
	gcc -g -ggdb -o 2.exe main_2.c manipula_array.s inverte_array.s